/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.contract.api;

import com.example.contract.model.ErrorResponse;
import com.example.contract.model.LoginRequest;
import com.example.contract.model.LoginResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.Map;

@Validated
@Tag(name = "auth", description = "the auth API")
public interface AuthApi {

    /**
     * POST /auth/login : Encrypted login
     * Receives the username and password encrypted with the server public RSA key. Validates the credentials and returns a short-lived JWT (5 minutes). 
     *
     * @param loginRequest  (required)
     * @return Login successful, JWT issued (status code 200)
     *         or Missing username or password (status code 400)
     *         or Unauthorized - invalid credentials or timestamp (status code 401)
     */
    @Operation(
        operationId = "authLoginPost",
        summary = "Encrypted login",
        description = "Receives the username and password encrypted with the server public RSA key. Validates the credentials and returns a short-lived JWT (5 minutes). ",
        responses = {
            @ApiResponse(responseCode = "200", description = "Login successful, JWT issued", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Missing username or password", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized - invalid credentials or timestamp", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )

    ResponseEntity<LoginResponse> authLoginPost(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    );

}
