/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.contract.api;

import com.example.contract.model.ErrorResponse;
import com.example.contract.model.JwkSet;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.Map;

@Validated
@Tag(name = "certs", description = "the certs API")
public interface CertsApi {

    /**
     * GET /certs : Retrieve the server public key
     * Returns the public RSA key of the Token Server in JWK format.
     *
     * @return Public JWK Set (status code 200)
     *         or Error retrieving public keys (status code 500)
     */
    @Operation(
        operationId = "certsGet",
        summary = "Retrieve the server public key",
        description = "Returns the public RSA key of the Token Server in JWK format.",
        responses = {
            @ApiResponse(responseCode = "200", description = "Public JWK Set", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = JwkSet.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error retrieving public keys", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/certs",
        produces = { "application/json" }
    )

    ResponseEntity<JwkSet> certsGet(

    );

}
