/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.contract.api;

import com.example.contract.model.ErrorResponse;
import com.example.contract.model.TokenIntrospectionRequest;
import com.example.contract.model.TokenIntrospectionResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.Map;

@Validated
@Tag(name = "introspect", description = "the introspect API")
public interface IntrospectApi {

    /**
     * POST /introspect : Validate JWT token
     * Validates a JWT and returns its status and decoded claims.
     *
     * @param tokenIntrospectionRequest  (required)
     * @return Token introspection result (status code 200)
     *         or Invalid token (status code 400)
     */
    @Operation(
        operationId = "introspectPost",
        summary = "Validate JWT token",
        description = "Validates a JWT and returns its status and decoded claims.",
        responses = {
            @ApiResponse(responseCode = "200", description = "Token introspection result", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TokenIntrospectionResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid token", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/introspect",
        produces = { "application/json" },
        consumes = { "application/json" }
    )

    ResponseEntity<TokenIntrospectionResponse> introspectPost(
        @Parameter(name = "TokenIntrospectionRequest", description = "", required = true) @Valid @RequestBody TokenIntrospectionRequest tokenIntrospectionRequest
    );

}
