/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.contract.api;

import com.example.contract.model.ErrorResponse;
import com.example.contract.model.TokenRequest;
import com.example.contract.model.TokenResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.Map;

@Validated
@Tag(name = "token", description = "the token API")
public interface TokenApi {

    /**
     * POST /token : Generate JWT token
     * Issue a signed JWT access token for a registered client.
     *
     * @param authorization Bearer token signed by the client using its private key (required)
     * @param tokenRequest  (required)
     * @return Token successfully generated (status code 200)
     *         or Invalid request body (status code 400)
     *         or Unauthorized - invalid or missing Authorization header (status code 401)
     *         or Forbidden - invalid client_id or body content (status code 403)
     */
    @Operation(
        operationId = "tokenPost",
        summary = "Generate JWT token",
        description = "Issue a signed JWT access token for a registered client.",
        responses = {
            @ApiResponse(responseCode = "200", description = "Token successfully generated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TokenResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request body", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized - invalid or missing Authorization header", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden - invalid client_id or body content", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/token",
        produces = { "application/json" },
        consumes = { "application/json" }
    )

    ResponseEntity<TokenResponse> tokenPost(
        @NotNull @Size(max = 5000) @Parameter(name = "Authorization", description = "Bearer token signed by the client using its private key", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Authorization", required = true) String authorization,
        @Parameter(name = "TokenRequest", description = "", required = true) @Valid @RequestBody TokenRequest tokenRequest
    );

}
