/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.contract.api;

import com.example.contract.model.ErrorResponse;
import com.example.contract.model.TokenAssertionRequest;
import com.example.contract.model.TokenResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.Map;

@Validated
@Tag(name = "token-classic", description = "the token-classic API")
public interface TokenClassicApi {

    /**
     * POST /token-classic : Generate JWT token (body-based client assertion)
     * Issues a new JWT access token using the client assertion flow. The client sends its signed JWT in the request body, following RFC 7523. 
     *
     * @param tokenAssertionRequest  (required)
     * @return Token successfully generated (status code 200)
     *         or Invalid or expired client assertion (status code 400)
     *         or Unauthorized - invalid signature or claim (status code 401)
     */
    @Operation(
        operationId = "tokenClassicPost",
        summary = "Generate JWT token (body-based client assertion)",
        description = "Issues a new JWT access token using the client assertion flow. The client sends its signed JWT in the request body, following RFC 7523. ",
        responses = {
            @ApiResponse(responseCode = "200", description = "Token successfully generated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TokenResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid or expired client assertion", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized - invalid signature or claim", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/token-classic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )

    ResponseEntity<TokenResponse> tokenClassicPost(
        @Parameter(name = "TokenAssertionRequest", description = "", required = true) @Valid @RequestBody TokenAssertionRequest tokenAssertionRequest
    );

}
